<?php
define('DOC_PAGE_ID', 30);
define('BUGS_PAGE_ID', 51);
define('FEATURES_PAGE_ID', 11);
define('BENEFITS_PAGE_ID', 13);
define('DEMO_PAGE_ID', 19);
define('ENTERPRISE_PAGE_ID', 2501);
define('ENTERPRISE_SERVICES_PAGE_ID', 2505);
define('CONTACT_FORM_SUBSCRIBE_ID', 2763);
define('CONTACT_FORM_DOWNLOAD_ID', 2764);
?>